spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
  messages:
    basename: messages
    encoding: UTF-8
    fallback-to-system-locale: false

  data:
    mongodb:
      uri: mongodb://localhost:27017/wedding_invitations

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://dev-ihzu1eqm6kr7z6rb.us.auth0.com/
          audience: https://allsetoAuth.com

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG

app:
  localization:
    supported-languages:
      - en
      - hy
      - ru
  pricing:
    base-price: 20000.0
  promo-codes:
    codes:
      - code: WELCOME10
        discount-type: PERCENTAGE
        discount-value: 10
        active: true

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
